with source as (
    select * from {{ source('airbyte_bq_test_srandle2', 'PropertyAmenities') }}
),

renamed as (
    select                   
        ifnull(UnitID,0) unitID,
        ifnull(Year,0) year,
        ifnull(MinRate,0) minRate,
        ifnull(MaxRate,0) maxRate,
        ifnull(AirHockey,0) airHockey,
        ifnull(Antenna,0) antenna,
        ifnull(ArcadeGame,0) arcadeGame,
        ifnull(Basketball,0) basketball,
        ifnull(Baths,'null') baths,
        ifnull(BBQCharcoal,0) bbqCharcoal,
        ifnull(BBQGas,0) bbqGas,
        ifnull(Bedrooms,0) bedrooms,
        ifnull(Beds,0) beds,
        ifnull(BumperPool,0) bumperPool,
        ifnull(BunkSets,0) bunkSets,
        ifnull(CableTV,0) cableTV,
        ifnull(Computer,0) computer,
        ifnull(Crib,0) crib,
        ifnull(Daybed,0) daybed,
        ifnull(DistanceToBeach,'null') distanceToBeach,
        ifnull(DuneDeck,0) duneDeck,
        ifnull(DoubleSleepSofas,0) doubleSleepSofas,
        ifnull(Duos,0) duos,
        ifnull(Elevator,0) elevator,
        ifnull(Fax,0) fax,
        ifnull(FireplaceGas,0) fireplaceGas,
        ifnull(FireplaceWood,0) fireplaceWood,
        ifnull(Foosball,0) foosball,
        ifnull(FourWheelDrive,0) fourWheelDrive,
        ifnull([`Full`],0) [`full`],
        ifnull(Futon,0) futon,
        ifnull(GatedPool,0) gatedPool,
        ifnull(HandicapFriendly,0) handicapFriendly,
        ifnull(HeatedPool,0) heatedPool,
        ifnull(HeatedPoolFee,'null') heatedPoolFee,
        ifnull(HeatedPoolDate,'null') heatedPoolDate,
        ifnull(HighChair,0) highChair,
        ifnull(Holidays,0) holidays,
        ifnull(HotTub,0) hotTub,
        ifnull(HPCostGuest,0) hpCostGuest,
        ifnull(HPCostIncluded,0) hpCostIncluded,
        ifnull(HPTypeHeatPump,0) hpTypeHeatPump,
        ifnull(HPTypePropane,0) hpTypePropane,
        ifnull(Icemaker,0) icemaker,
        ifnull(InternetAccess,0) internetAccess,
        ifnull(InternetCable,0) internetCable,
        ifnull(InternetDSL,0) internetDSL,
        ifnull(InternetSatellite,0) internetSatellite,
        ifnull(KeylessEntry,0) keylessEntry,
        ifnull(Kings,0) kings,
        ifnull(LinenCharge,'null') linenCharge,
        ifnull(Linens,0) linens,
        ifnull(MasterBedrooms,0) masterBedrooms,
        ifnull(MaxOccupancy,'null') maxOccupancy,
        ifnull(MunicipalWater,0) municipalWater,
        ifnull(NewConstructionProject,0) newConstructionProject,
        ifnull(NewConstruction,0) newConstruction,
        ifnull(NoSmoking,0) noSmoking,
        ifnull(NoSpecialEvents,0) noSpecialEvents,
        ifnull(PackNPlay,0) packNPlay,
        ifnull(PageNumber,0) pageNumber,
        ifnull(Parking,'null') parking,
        ifnull(PetsAllowed,0) petsAllowed,
        ifnull(PingPong,0) pingPong,
        ifnull(PlayPen,0) playPen,
        ifnull(PoolSize,'null') poolSize,
        ifnull(PoolSideCabana,0) poolSideCabana,
        ifnull(PoolTable,0) poolTable,
        ifnull(PortaCrib,0) portaCrib,
        ifnull(PrivatePool,0) privatePool,
        ifnull(PrivateWell,0) privateWell,
        ifnull(PrivatePoolDates,'null') privatePoolDates,
        ifnull(Queens,0) queens,
        ifnull(QueenSleepSofas,0) queenSleepSofas,
        ifnull(RentalsBookPageNumber,0) rentalsBookPageNumber,
        ifnull(SatelliteTV,0) satelliteTV,
        ifnull(ScreenedPorch,0) screenedPorch,
        ifnull(SleepSofas,0) sleepSofas,
        ifnull(SpecialEvents,0) specialEvents,
        ifnull(SpecialEventsDeposit,'null') specialEventsDeposit,
        ifnull(SpecialEventsFee,'null') specialEventsFee,
        ifnull(TheaterRoom,0) theaterRoom,
        ifnull(Towels,0) towels,
        ifnull(Traditional,0) traditional,
        ifnull(Trundles,0) trundles,
        ifnull(Twins,0) twins,
        ifnull(UnitNumber,'null') unitNumber,
        ifnull(VolleyBallSet,0) volleyBallSet,
        ifnull(WalkwayToBeach,0) walkwayToBeach,
        ifnull(WaterTreatmentSystem,0) waterTreatmentSystem,
        ifnull(WetBar,0) wetBar,
        ifnull(WhirlpoolTub,0) whirlpoolTub,
        ifnull(Wireless,0) wireless,
        ifnull(DoubleBunkSets,0) doubleBunkSets

    from source

)

select * from renamed